sudo: required
language: node_js
node_js:
- 10
deploy:
  provider: heroku
  api_key:
    secure: L+Qnl5JP3+9xsdt5khl37fQRYxY5NC+zuvDgqWfF4KUxjcosh5MBkt7wfK6at5+Fb+aVLZkJXlR2WiuJzYNlertlvgFGgqcSIpccII5Mx+Oi2GSUa3Co4Z3klWdvxxiojRxdLNmuSGJ5NxlZAe4kDZY67dt+wGIbweVrbczlxtKqXuirFhTzt84eGnVQUG09NqRcYO/G+DXnQPOY3ZtsyLs4a0J7oZZhCCq7oHVZOM2e1+y2mG3edO0JgZGYZYNa/fLL+sryaGqfrseJ/9QKDqa+FK2YMiT2RZ4vdoI4ATS1WsSQKkLPGwinqPtUViQrd5fgAzrwcoOiQuHpIPLC9mtyiNfOiaY69nZLeODVhlJtZpXWENGMCATRJAZ7VzA/OjNddKMgZq+X5c3TCaSb0iH6cIoulRD6FADt9UYxHmTs3P2xgCLRpzgEC0rYDyK3WUX4rYY9qr/dYuE3jPxPyKYu+BlQEjl09q6xfJC+1elxuOa6kdh2qfCK6N/tIpueKlkQugfjqVX8cDIa1X8Vd7NOxyrt3ZNe/fshwYOur903jXg7sZrMIugY57BxQ0bJeHegF5Jf79pcTIsXFoUbEDwXo3cxouS0et2rAl3ml3QN9QalvOahJyLNND88W3niLd0HOYCO02K+AF4RHPJLfs+ogkyH4rqSYC78rQBVg0A=
  app:
    master: sae-akgec

